name: CI

concurrency:
  group: ci-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/vietanhduong/go-bpf-debug:202310041102
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go env
        uses: actions/setup-go@v4
        with:
          go-version: "1.18.x"
      - name: Print system info
        run: |
          cat /etc/os-release
          uname -a
      - name: Run integration tests
        run: |
          sudo go test -tags integration -v ./...
